void matrix_init(void);
void init_position(void);
int controllo_ostacoli_vittoria(void);
void muoviti(void);
void cambiaDirezione(int dir);
int getX(void);
int getY(void);
int getObstacleX(void);
int getObstacleY(void);
int getDir(void);
void segnaOstacolo(int x, int y);
void clearObstacles(void);
